apiVersion: apps/v1
kind: Deployment
metadata:
  name: homara-backend
  namespace: homara
  labels:
    app: homara-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homara-backend
  template:
    metadata:
      labels:
        app: homara-backend
    spec:
      containers:
        - name: backend
          image: homara-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@homara-db:5432/homara?schema=public
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: production
            - name: JWT_SECRET
              value: homara_jwt_secret_key_2026_secure
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: homara-backend
  namespace: homara
spec:
  type: NodePort
  selector:
    app: homara-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
