apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homara-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ImKrav/HomaraBackend.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homara
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homara-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ImKrav/HomaraFrontend.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homara
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
